// <auto-generated />
using System;
using CosmicGameAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmicGameAPI.Migrations
{
    [DbContext(typeof(CosmicDbContext))]
    partial class CosmicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("CosmicGameAPI.Entities.BhavaPlanet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bhavalst")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChartHolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Palenetlst")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("BhavaPlanets");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.ChartHolder", b =>
                {
                    b.Property<int>("ChartHolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ayanamasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("AyanamasaPolicy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BirthTimeRectified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChartType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildName")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FatherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseSystem")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatLocator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LngLocator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("RectifiedTOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChartHolderId");

                    b.ToTable("ChartHolders");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("AreasCovered")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountOfTimeZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DSTFromTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DSTToTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDST")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfTimeZone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTimeZone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearFrom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.CurrentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatLocator")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LngLocator")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CurrentAddresses");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.U_Lev4_S4SL_Register", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DMS")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ext_Line")
                        .HasColumnType("TEXT");

                    b.Property<double?>("KC_INDEX")
                        .HasColumnType("REAL");

                    b.Property<string>("KC_Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("KC_Rasi_Lord")
                        .HasColumnType("TEXT");

                    b.Property<string>("KC_Rasi_Lord_SPL")
                        .HasColumnType("TEXT");

                    b.Property<double?>("LineNo")
                        .HasColumnType("REAL");

                    b.Property<string>("S1SL")
                        .HasColumnType("TEXT");

                    b.Property<double?>("S1SLCount")
                        .HasColumnType("REAL");

                    b.Property<string>("S2SL")
                        .HasColumnType("TEXT");

                    b.Property<double?>("S2SLCount")
                        .HasColumnType("REAL");

                    b.Property<string>("S3SL")
                        .HasColumnType("TEXT");

                    b.Property<double?>("S3SLCount")
                        .HasColumnType("REAL");

                    b.Property<string>("S4SL")
                        .HasColumnType("TEXT");

                    b.Property<double?>("S4SLCount")
                        .HasColumnType("REAL");

                    b.Property<double?>("S4SL_ArcDist")
                        .HasColumnType("REAL");

                    b.Property<double?>("StarCount")
                        .HasColumnType("REAL");

                    b.Property<string>("StarLord")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VimsoPeriod")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("u_Lev4_S4SL_Registers");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsActive")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsAllowMultipelLogin")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsApproved")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsDelete")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.UserLoginInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Browser")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IsLogin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserLoginInfos");
                });

            modelBuilder.Entity("CosmicGameAPI.Entities.VimsoMasterRegister", b =>
                {
                    b.Property<int>("LineNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("An_Gp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DMS")
                        .HasColumnType("TEXT");

                    b.Property<int>("Di_Gp")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Moving_Distance")
                        .HasColumnType("REAL");

                    b.Property<string>("Pre_S4SL_ArcDist")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pu_Gp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rasi_L")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rasi_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("S1SL")
                        .HasColumnType("TEXT");

                    b.Property<string>("S2SL")
                        .HasColumnType("TEXT");

                    b.Property<string>("S3SL")
                        .HasColumnType("TEXT");

                    b.Property<string>("S4SL")
                        .HasColumnType("TEXT");

                    b.Property<double>("S4SL_ArcDist")
                        .HasColumnType("REAL");

                    b.Property<int>("So_Gp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StarLord")
                        .HasColumnType("TEXT");

                    b.Property<string>("StarName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Star_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Vimso_pd")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineNo");

                    b.ToTable("VimsoMasterRegisters");
                });
#pragma warning restore 612, 618
        }
    }
}
